[theme]
base = "light"
primaryColor = "#176B68"
backgroundColor = "#F7F5EF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17252A"
font = "sans serif"

[server]
maxUploadSize = 100
headless = true

[browser]
gatherUsageStats = false
